### ISSUE TITLE
spillover compensation

### ISSUE THREAD

**Issue by wulab2020** [BodenmillerGroup/IMCWorkflow#3]
For IMC data analysis, we are curious how the spillover compensation is carried. Can you pls point us to the sample codes? Thanks!

**Comment by nilseling** [comment]
Hi @wulab2020 

thanks for reaching out! Please find all information (experimental and computational) at https://bodenmillergroup.github.io/IMCDataAnalysis/spillover-correction.html. Also have a look at https://bodenmillergroup.github.io/IMCDataAnalysis/prerequisites.html how to obtain the example data.
Best,

Nils

**Comment by nilseling** [comment]
I assume this has been resolved. Please reopen if anything is unclear.
